spring:
  application:
    name: medDesk

  # This allows the H2 console or Swagger to be accessed if you add them later
  h2:
    console:
      enabled: true

  # Useful for seeing what's happening during development
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# Custom property to toggle security (Optional - for advanced users)
app:
  security:
    enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha # Sorts endpoints alphabetically
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiration: 3600000 # 1 hour in ms
  refresh-token-expiration: 604800000 # 7 days


# --- MONITORING AND OBSERVABILITY ---

management:
  metrics:
    tags:
      application: meddesk-app
  endpoints:
    web:
      exposure:
        # we expose health and prometheus so the monitors can see our data
        include: "health,info,prometheus"
  tracing:
    sampling:
      # 1.0 means we capture every single request (100%)
      probability: 1.0
  zipkin:
    tracing:
      # this must match the service name 'zipkin' in docker-compose
      endpoint: "http://zipkin:9411/api/v2/spans"

logging:
  pattern:
    # this line adds [appName, traceId, spanId] to your logs
    # very useful to find which log belongs to which request in Zipkin
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"